
declare @jfunctionid int
select @jfunctionid=30600
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('06004','Tissue & Tissue Dispenser',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('08007','Exhibition Supplies',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03006','Refrigeration Equipment',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('06005','Bathroom Supplies',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('09005','Others ',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03013','Measuring Instruments ',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('07006','Accessories',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('003','Kitchen Ware and Equipment',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('02005','Disposable Tableware',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('09002','Tabletop Decoration',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('01001','Bar Equipment',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03001','Cooking Equipment',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('005','Lobby & Cleaning Equipments and Supplies',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03007','Chef s Worktop',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('05006','Laundry Equipment',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('007','Linen and Signs',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('07004','Curtain',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03012','Kitchen Cutlery',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('07002','Towels ',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('07007','Signs',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03011','Storage Containers',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('02001','Ceramic Tableware',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('08004','Fire-fighting Equipment',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('008','Engineering Equipments',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('06006','Bathroom Hardware & Accessories',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('05001','Lobby Supplies',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('08008','Decorative Lighting',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03014','Kitchen Protection',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('09001','Vase',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('002','Tableware and Restaurant supplies',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('004','Furniture',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('06001','Guest Room Electric Appliance ',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('02006','Buffet Service Utensil',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('08001','Elevator',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('04004','Outdoor Furniture',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('001','Bar Equipments & Supplies',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('05004','Cleaning Tools',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('01002','Bar Utensils',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('006','Guestroom Supplies and Equipments',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('04002','Dining-room Furniture',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('08002','Maintenance Equipment& Tools',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('07003','Restaurant Textile',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03008','Dishwasher',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('07005','Uniform',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03005','Pre-processing Food Machine',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('009','Decoration and Artware',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('06002','Guest Room Supplies',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('02003','Stainless Steel Tableware',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('05003','Cleaning Machinery',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('06003','Disposable Product',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03015','Retail Equipment',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03009','Heat Preservation Showcase',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03003','Baking Equipment',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('07001','Bedding Supplies',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('08003','Walkie',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('08006','Sanitary Ware',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('09004','Festival Gifts',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03002','Cooking Utensil',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('02004','Plastic & Melamine Tableware',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('05002','Front Desk & Business Center Equipment',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('02002','Glass & Crystal Tableware',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('04003','Conference Supplies',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('09003','Wall Decoration',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('04001','Guest Room Furniture',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03004','Baking Utensil',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('08005','Intelligence Control System',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('03010','Serving cart',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('07008','Other Textile',@jfunctionid)
insert into tbasicsort (jclasscode,jclassname,jfunctionid) values('05005',' Chemical Detergent',@jfunctionid)
